<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;
use Atom\Auth\AbacPolicyStore;
use Atom\Security\SecretRedactor;

/**
 * Phase 48 — AbacPolicyStore unit tests (6 tests).
 */
class AbacPolicyStoreTest extends TestCase
{
    private AbacPolicyStore $store;

    protected function setUp(): void
    {
        parent::setUp();
        $this->store = new AbacPolicyStore(new SecretRedactor());
    }

    public function testDefaultPoliciesSeeded(): void
    {
        $this->assertGreaterThanOrEqual(3, $this->store->count());
        $policy = $this->store->getPolicy('POLICY_TOPSECRET_VAULT');

        $this->assertNotNull($policy);
        $this->assertSame('PERMIT', $policy['effect']);
        $this->assertArrayHasKey('target', $policy);
        $this->assertArrayHasKey('rules', $policy);
    }

    public function testAddCustomPolicy(): void
    {
        $customPolicy = [
            'id' => 'POLICY_CUSTOM_AUDIT',
            'title' => 'Custom Audit Read Rule',
            'effect' => 'PERMIT',
            'target' => ['resource_type' => 'audit_log', 'actions' => ['read']],
            'rules' => [
                ['category' => 'subject', 'attribute' => 'role', 'operator' => 'equals', 'value' => 'auditor'],
            ],
        ];

        $this->store->addPolicy($customPolicy);

        $retrieved = $this->store->getPolicy('POLICY_CUSTOM_AUDIT');
        $this->assertNotNull($retrieved);
        $this->assertSame('Custom Audit Read Rule', $retrieved['title']);
    }

    public function testRemovePolicy(): void
    {
        $this->store->addPolicy(['id' => 'POLICY_TEMP', 'target' => [], 'rules' => []]);
        $this->assertNotNull($this->store->getPolicy('POLICY_TEMP'));

        $removed = $this->store->removePolicy('POLICY_TEMP');
        $this->assertTrue($removed);
        $this->assertNull($this->store->getPolicy('POLICY_TEMP'));
    }

    public function testListPoliciesReturnsAll(): void
    {
        $list = $this->store->listPolicies();
        $this->assertIsArray($list);
        $this->assertCount($this->store->count(), $list);
    }

    public function testGetNonExistentPolicyReturnsNull(): void
    {
        $this->assertNull($this->store->getPolicy('NON_EXISTENT_ID'));
    }

    public function testAutoGeneratedPolicyIdWhenMissing(): void
    {
        $this->store->addPolicy([
            'title' => 'Anonymous Policy',
            'target' => [],
            'rules' => [],
        ]);

        $list = $this->store->listPolicies();
        $lastPolicy = end($list);
        $this->assertNotEmpty($lastPolicy['id']);
        $this->assertStringStartsWith('policy_', $lastPolicy['id']);
    }
}
